CREATE TRIGGER trigger_name .. DISABLE;

CREATE TABLE TEST1 (DUMMY VARCHAR2(9));

CREATE OR REPLACE TRIGGER TRXX 
BEFORE INSERT ON TEST1
DISABLE   --> LAST CLAUSE
BEGIN
  DBMS_OUTPUT.PUT_LINE('INSERTING RECORDS...');
END;
/

set serveroutput on;
INSERT INTO TEST1 VALUES ('A');

ALTER TRIGGER TRXX ENABLE;

INSERT INTO TEST1 VALUES ('B');

COMMIT;

ALTER TRIGGER trigger_name DISABLE|ENABLE;

ALTER TRIGGER trigger_name COMPILE [DEBUG] compiler_parameter [REUSE SETTINGS];

ALTER TRIGGER trigger_name RENAME TO trigger2;

DROP TRIGGER trigger_name;



SELECT * FROM USER_TRIGGERS;

-- TEAR DOWN 
DROP TABLE TEST1 PURGE;

SELECT * FROM v$session_longops;